apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forex-exporter
  name: forex-exporter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: forex-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9299"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: forex-exporter
    spec:
      containers:
      - env:
        - name: FOREX_EXPORTER_LISTEN
          value: ":9299"
        - name: FOREX_EXPORTER_CURRENCY_PAIRS
          value: "USD/GBP,USD/EUR"
        - name: FOREX_EXPORTER_TWELVEDATA_API_KEY
          valueFrom:
            secretKeyRef:
              key: apikey
              name: forex-exporter
        image: icydoge/web:forex-exporter-8e80984
        imagePullPolicy: IfNotPresent
        name: forex-exporter
        ports:
        - containerPort: 9299
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 25
---
apiVersion: v1
data:
  apikey: WU9VUl9BUElfS0VZX0hFUkU= # Your base64-encoded API key here
kind: Secret
metadata:
  name: forex-exporter
  namespace: default
type: Opaque